yolo_model:

  config_file:
    name: yolov3-tiny_MAVIC.cfg
  weight_file:
    name: yolov3-tiny_MAVIC.weights
  threshold:
    value: 0.6
  detection_classes:
    names:
      - bicycle
      - bus
      - car
      - motorcycle
      - person
      - truck

