yolo_model:

  config_file:
    name: yolov3-tiny-obj.cfg
  weight_file:
    name: yolov3-tiny-obj_last.weights
  threshold:
    value: 0.3
  detection_classes:
    names:
      - person
      - car
      - bus
      - tree
      - building

